{
 "title": "Logging dashboard via Loki",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "search_term", "label": "Search Logs" }
  ]
 },
 "panels": [
  {
   "title": "Total Count of logs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({application=\"my-app\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Count of error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({application=\"my-app\"} |= \"error\" [$__range]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{application=\"my-app\"} |~ `(?i)$search_term`"
    }
   ]
  },
  {
   "title": "error rate (msg/min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service) (rate({application=\"my-app\"} |~ \"DB connection failed|Cache service unavailable|Backend failed|Invalid user|backend error\" [1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "error By Service",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service) (count_over_time({application=\"my-app\"} |~ \"downstream DB error|DB connection failed|Cache service unavailable|Invalid user session token|failed due to backend error\" [$__range]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (service) (count_over_time({application=\"my-app\"} |~ \"downstream DB error|DB connection failed|Cache service unavailable|Invalid user session token|failed due to backend error\" [$__range]))",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}